export const colors = {
    error: "#b31b25",
    primaryContainer: "#8cfeca",
    surfaceContainer: "#e6e8eb",
    surfaceContainerLow: "#eff1f3",
    onSecondaryContainer: "#005d4b",
    onTertiary: "#ddf7ff",
    onSurface: "#2c2f31",
    onBackground: "#2c2f31",
    tertiaryFixed: "#00dcfe",
    secondaryDim: "#005b49",
    onPrimary: "#c8ffe1",
    errorDim: "#9f0519",
    primaryFixed: "#8cfeca",
    outlineVariant: "#abadaf",
    onSecondary: "#c4ffeb",
    surfaceContainerLowest: "#ffffff",
    surfaceDim: "#d1d5d8",
    surfaceContainerHighest: "#dadde0",
    onSecondaryFixedVariant: "#006854",
    onPrimaryFixedVariant: "#006d4b",
    onPrimaryFixed: "#004d34",
    errorContainer: "#fb5151",
    onSurfaceVariant: "#595c5e",
    onTertiaryFixedVariant: "#005361",
    onErrorContainer: "#570008",
    tertiaryDim: "#005866",
    surfaceBright: "#f5f6f8",
    tertiary: "#006575",
    secondaryFixedDim: "#45edc6",
    outline: "#757779",
    background: "#f5f6f8",
    onTertiaryFixed: "#00333d",
    primaryFixedDim: "#7eefbc",
    onTertiaryContainer: "#004956",
    surfaceContainerHigh: "#e0e3e5",
    tertiaryFixedDim: "#00cded",
    surface: "#f5f6f8",
    secondaryContainer: "#58fcd4",
    secondary: "#006854",
    inversePrimary: "#8cfeca",
    onPrimaryContainer: "#006243",
    secondaryFixed: "#58fcd4",
    surfaceTint: "#006948",
    onError: "#ffefee",
    tertiaryContainer: "#00dcfe",
    primaryDim: "#005b3f",
    primary: "#006948",
    onSecondaryFixed: "#00483a",
    inverseOnSurface: "#9b9d9f",
    inverseSurface: "#0c0f10",
    surfaceVariant: "#dadde0"
};

// Simple theme export to apply consistently across pages.
// This repo currently uses Bootstrap + custom CSS, so we expose theme values
// via CSS variables and a lightweight provider.
export const theme = {
  colors,
};
